### ISSUE TITLE
普通产品设备必须添加子设备才能正常适用

### ISSUE THREAD

**Issue by mywsat** [mqttsnet/thinglinks#13]
1.
COMMON：普通产品，需直连设备。
GATEWAY：网关产品，可挂载子设备。
目前COMMON普通产品还需要添加子设备才能正常适用 逻辑和网关产品重复
2.
采用Redis分布式锁进程出现无法获取连接情况，是否需要优化连接策略

**Comment by xiaonannet** [comment]
普通产品及设备的协议正在优化，普通设备可直接上报datasTopic报文。
redis问题稍后会进行核查，可尝试修改配置参数增加超时时间

**Comment by xiaonannet** [comment]
已处理
