### ISSUE TITLE
TDengine3.0兼容问题（创建超级表失败）

### ISSUE THREAD

**Issue by yylljun** [mqttsnet/thinglinks#15]
TDengine3.0创建超级表时列名不能带，【''】单引号。eg:
创建失败
create STABLE if not exists thinglinks.GATEWAY_fe6fa6f1f63746adbd3fb867216c0d98_gas_device_1('ts' timestamp,'event_time' timestamp,'a01011' double,'a01012' double,'a01013' double) tags('device_identification' binary(64));
创建成功
create STABLE if not exists thinglinks.GATEWAY_fe6fa6f1f63746adbd3fb867216c0d98_gas_device_1(ts timestamp,event_time timestamp,a01011 double,a01012 double,a01013 double) tags(device_identification binary(64));

**Comment by andyz168** [comment]
把单引号去掉就行
