### ISSUE TITLE
设备在线/离线如何操作

### ISSUE THREAD

**Issue by zqqiang0307** [mqttsnet/thinglinks#38]
只看到更新子设备的topic，普通设备和网关设备怎么更新在线/离线，是有接收心跳的topic吗？

**Comment by xiaonannet** [comment]
网关设备和普通设备在线离线可以查看MqttEvent 事件，broker会把mqtt的整个生命周期事件推送到rocketmq，DeviceActionMessageConsumer会处理全部事件。子设备需要网关设备进行topic的上报，告知平台在线离线情况，详情可查看：http://showdoc.mqttsnet.com/web/#/5/80 ；操作视频及教程在知识星球
