### ISSUE TITLE
为什么我上传nacos配置文件导入到nacos中导不进去呢，帮看看谢谢

### ISSUE THREAD

**Issue by aozeyu** [mqttsnet/thinglinks#52]
是我压缩错w文件夹了吗，应该没错吧，这个defaut gruop文件夹
@lvwshuai @kangkaime 
<img width="1549" alt="截屏2023-09-15 22 13 24" src="https://github.com/mqttsnet/thinglinks/assets/55688386/527e2812-7ff7-4807-9938-1704bac1067c">

**Comment by aozeyu** [comment]
<img width="768" alt="截屏2023-09-15 22 15 18" src="https://github.com/mqttsnet/thinglinks/assets/55688386/c744ce34-a8de-409a-92ab-e191621c86c1">

**Comment by xiaonannet** [comment]
可重新压缩后重试下，部分压缩工具可能会导致文件受损；或调整nacos版本后重试下，官方推荐的nacos版本为2.1.0左右

**Comment by aozeyu** [comment]
@xiaonannet  确实是nacos版本导致的问题，谢谢，已解决了
