### ISSUE TITLE
TDengine2.6+,TDengine3.0.1.4 创建子表失败问题

### ISSUE THREAD

**Issue by wulongbo** [mqttsnet/thinglinks#54]
环境说明：使用的是没有更新kafka的版本，TDengine2.6+,TDengine3.0.1.4 版本都尝试过。
在子设备管理模块  调用刷新子设备数据模型接口（refreshDeviceInfoDataModel） 或者
设备管理模块创建普通设备 的时候 都会去创建子表，这时候一直报错
create table
                if not exists thinglinks.GATEWAY_cb97f8c2a98447f5a916e8266cebeb95_hongwai_service_74c24f22e7944f649847b90de6193693
                using thinglinks.GATEWAY_cb97f8c2a98447f5a916e8266cebeb95_hongwai_service
                tags
         (  
            sensortest
         )
![0f56b9ca79a875a3ab0582f1230c045](https://github.com/mqttsnet/thinglinks/assets/43068601/3efa2a7c-9ff6-4700-8c34-3f2ee8f63019)
解决方案：tags标签插入问题，在动态sql处加入单引号。

    <update id="createTable">
        create table
                if not exists #{dataBaseName}.#{tableName}
                using #{dataBaseName}.#{superTableName}
                tags
        <foreach item="item" collection="tagsFieldValues" separator=","
                 open="(" close=")" index="">
            '${item.fieldValue}'
        </foreach>
    </update>
![image](https://github.com/mqttsnet/thinglinks/assets/43068601/3200569a-499c-416f-9fd5-5fa234ef25de)

**Comment by xiaonannet** [comment]
请更新至最新代码，commitRecord ：https://github.com/mqttsnet/thinglinks/commit/c33f4536292359ff137240cc1bf34f5944d036a9
