### ISSUE TITLE
TDengine查询问题 1.库中数据已插入库中 2.控制台执行查询脚本，可以查询到数据 3.代码执行查询结果是200，但是结果元素显示都是空的

### ISSUE THREAD

**Issue by xuyuanzhong** [mqttsnet/thinglinks#56]
1.库中数据已插入库中
2.控制台执行查询脚本，可以查询到数据
3.代码执行查询结果是200，但是结果元素显示都是空的

**Comment by xuyuanzhong** [comment]
https://mqttsnet.yuque.com/trgbro/fycq04/fdd40apv0y6mnay9按照这个方案操作下tdServer

**Comment by xiaonannet** [comment]
原因：因为Tdengine SQL 查询中如果使用了函数，返回的结果字段中会包含函数名，会导致ThingLinks存在解析问题，需要修改Tdengine Server配置文件，重启Tdengine 服务。 

[gine官方配置文件详解](https://docs.taosdata.com/reference/config/#keepcolumnname)

解决方案：

![image](https://github.com/mqttsnet/thinglinks/assets/57425893/bb74ad6f-f49a-42c1-99a2-f55f1b246df8)

添加以下配置内容
![image](https://github.com/mqttsnet/thinglinks/assets/57425893/00339d0d-6a3a-41b7-a56e-9409aa473ce2)
