### ISSUE TITLE
MQTT创建子设备失败

### ISSUE THREAD

**Issue by leonJiang1992** [mqttsnet/thinglinks#79]
MQTT创建子设备 获取不到用户信息,导致空指针异常
<img width="383" alt="a337f0410225e0393c0f40a36192f3e" src="https://github.com/user-attachments/assets/603bfe32-06ed-4c75-8f0d-88968387bace">

**Comment by xiaonannet** [comment]
We have fixed this issue and you can see the commit history at the link below.
[commit](https://github.com/mqttsnet/thinglinks/commit/441b9cdf60fe191359f6bbf986d5406cfa2d8cd8)
