### ISSUE TITLE
网关子设备MQTT上报数据失败

### ISSUE THREAD

**Issue by leonJiang1992** [mqttsnet/thinglinks#82]
通过MQTT向平台网关子设备上报数据,发现一直出现processingDeviceDataTopic Device not found 提示
检查原因为后台在redis中无法找到子设备的device信息
![image](https://github.com/user-attachments/assets/bb0d3294-b818-477d-8aec-1bb26f431634)
检查未发现有服务会更新redis 子设备信息.该问题导致网关子设备无法上报数据

**Comment by xiaonannet** [comment]
We have fixed this issue and you can see the commit history at the link below.

[commit](https://github.com/mqttsnet/thinglinks/commit/441b9cdf60fe191359f6bbf986d5406cfa2d8cd8)
