### ISSUE TITLE
代码的feignclient类的意思

### ISSUE THREAD

**Issue by xmgh1024** [mqttsnet/thinglinks#85]
BifroMQApi这个类中的url属性 url = "${" + Constants.PROJECT_PREFIX + ".feign.bifromq.bifromq-api-server:http://127.0.0.1:8091}" 代表什么意思？这个地址 http://127.0.0.1:8091是哪个服务的地址，看起来像seata服务的。但是，这个类是向mq发送消息的类型，所以比较迷茫。还请帮忙解惑，感谢

**Comment by xiaonannet** [comment]
BifroMQApi ：feign.bifromq.bifromq-api-server是调用mqtt broker（bifromq）api进行推送消息的，bifromq的默认rpc 端口是8091，代码中这个表达式的意思是优先取nacos中定义的url，如果没有配置就走代码默认写的ip+port
